dbt_dev_dbricks:
  outputs:
    dev:
      catalog: dbt_dev
      host: dbc-4316a65c-f5c3.cloud.databricks.com
      http_path: /sql/1.0/warehouses/8daf284fc69037d2
      schema: default
      threads: 1
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      type: databricks
    prod:
      catalog: dbt_prod
      host: dbc-4316a65c-f5c3.cloud.databricks.com
      http_path: /sql/1.0/warehouses/8daf284fc69037d2
      schema: default
      threads: 1
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      type: databricks
  target: dev













